// Package python is Doré's Python host-language backend.
package python

import (
	"encoding/json"
	"fmt"
	"strconv"
	"strings"

	"github.com/christopherwolf/dore/internal/ast"
	"github.com/christopherwolf/dore/internal/backend"
	"github.com/christopherwolf/dore/internal/types"
)

// Backend targets CPython 3.
type Backend struct {
	// Interpreter is the python executable to run. Empty means "python3".
	Interpreter string
}

func (b Backend) Name() string { return "python" }

func (b Backend) Extension() string { return ".py" }

func (b Backend) Command(harnessPath string) (string, []string) {
	interp := b.Interpreter
	if interp == "" {
		interp = "python3"
	}
	// -I isolates the interpreter: no user site-packages, no PYTHON* env vars.
	// -B keeps __pycache__ out of the user's tree.
	return interp, []string{"-I", "-B", harnessPath}
}

// Marshal renders a Doré value as a Python expression.
//
// Doré's semantics are preserved rather than approximated: money becomes a
// Decimal, never a float, because a spec that says 49.99 means exactly that.
func Marshal(v types.Value) (string, error) {
	switch v.Type.Kind {
	case types.Bool:
		if v.Bool {
			return "True", nil
		}
		return "False", nil
	case types.Text:
		return pyString(v.Text), nil
	case types.Int, types.I32, types.I64:
		return v.Int.String(), nil
	case types.Money, types.Decimal:
		return fmt.Sprintf("Decimal(%s)", pyString(v.String())), nil
	case types.Float:
		return strconv.FormatFloat(v.Float, 'r', -1, 64), nil
	case types.Date:
		return fmt.Sprintf("date(%d, %d, %d)", v.Date.Year(), int(v.Date.Month()), v.Date.Day()), nil
	}
	return "", &backend.ErrUnsupported{Backend: "python", Type: v.Type.String()}
}

// pyString renders a Go string as a Python string literal. JSON's escaping is
// a subset of Python's, so the encoding round-trips safely.
func pyString(s string) string {
	b, _ := json.Marshal(s)
	return string(b)
}

// Harness renders a program that calls fn once per touchstone row and writes
// one JSON line per row to stdout.
//
// Every row runs even after one fails, so a single assay reports every failing
// case rather than only the first.
func (b Backend) Harness(fn *ast.FnDecl, implPath string) (string, error) {
	var w strings.Builder

	module := moduleName(implPath)
	w.WriteString(`# Generated by dore. Do not edit.
import json, os, sys
from decimal import Decimal
from datetime import date

# The interpreter runs with -I, which drops the script directory from sys.path
# along with user site-packages. Put just this directory back, so the harness
# can import the implementation beside it and nothing else.
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

`)
	fmt.Fprintf(&w, "import %s as _impl\n\n", module)

	fmt.Fprintf(&w, "_fn = getattr(_impl, %s, None)\n", pyString(fn.Name))
	fmt.Fprintf(&w, `if _fn is None:
    print(json.dumps({"table": -1, "row": -1, "outcome": "failed",
                      "message": "%s does not define %s"}))
    sys.exit(0)

`, module, fn.Name)

	w.WriteString(`def _canon(v):
    # Canonical text, not JSON: an arbitrary-precision int or an exact
    # Decimal cannot survive a JSON number. Doré parses these back itself.
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, int):
        return str(v)
    if isinstance(v, Decimal):
        return str(v)
    if isinstance(v, float):
        return repr(v)
    if isinstance(v, str):
        return v
    if isinstance(v, date):
        return v.isoformat()
    raise TypeError("cannot represent %r (%s)" % (v, type(v).__name__))


def _emit(rec):
    sys.stdout.write(json.dumps(rec) + "\n")


def _run(table, row, args):
    try:
        value = _fn(*args)
    except Exception as exc:
        _emit({"table": table, "row": row, "outcome": "raised",
               "error": type(exc).__name__, "message": str(exc)})
        return
    try:
        _emit({"table": table, "row": row, "outcome": "returned",
               "repr": _canon(value)})
    except TypeError as exc:
        _emit({"table": table, "row": row, "outcome": "failed",
               "message": str(exc)})


`)

	for ti, table := range fn.Tables() {
		for ri, row := range table.Rows {
			args, err := rowArgs(fn, table, row)
			if err != nil {
				return "", err
			}
			fmt.Fprintf(&w, "_run(%d, %d, [%s])\n", ti, ri, strings.Join(args, ", "))
		}
	}
	return w.String(), nil
}

// rowArgs marshals one row's input cells in the order the signature declares,
// which is not necessarily the order the table's columns appear in.
func rowArgs(fn *ast.FnDecl, table *ast.Table, row ast.Row) ([]string, error) {
	byName := map[string]string{}
	for ci, col := range table.Columns {
		if col.Kind != ast.ColInput || ci >= len(row.Cells) {
			continue
		}
		lit, err := Marshal(row.Cells[ci].Value)
		if err != nil {
			return nil, err
		}
		byName[col.Name] = lit
	}

	args := make([]string, 0, len(fn.Params))
	for _, p := range fn.Params {
		lit, ok := byName[p.Name]
		if !ok {
			return nil, fmt.Errorf("no cell for input %q", p.Name)
		}
		args = append(args, lit)
	}
	return args, nil
}

// moduleName turns a path into an importable module name.
func moduleName(implPath string) string {
	name := implPath
	if i := strings.LastIndexAny(name, "/\\"); i >= 0 {
		name = name[i+1:]
	}
	return strings.TrimSuffix(name, ".py")
}
